/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrame;

import kelas.DataKitab;
import kelas.DataPengajar;
import kelas.DataKelas;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cherly
 */
public class DataKitab_Frame extends javax.swing.JPanel {

    /**
     * Creates new form DataKitab_Frame
     */
    public DataKitab_Frame() {
        initComponents();
        load_table();
        CBKelas();
        CBPengajar();
        resetForm();
        autoId();
    }
    
    void CBKelas() {
        if (cmbKelas == null) return;
        cmbKelas.removeAllItems();
        cmbKelas.addItem("-- Pilih Kelas --");
        
        DataKelas kls = new DataKelas();
        try (ResultSet rs = kls.dataComboBox()) {
            while (rs.next()) {
                cmbKelas.addItem(rs.getString("nama_kelas"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data Kelas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void CBPengajar() {
        if (cmbPengajar == null) return;
        cmbPengajar.removeAllItems();
        cmbPengajar.addItem("-- Pilih Pengajar --");
        
        
        DataPengajar pjr = new DataPengajar();
        try (ResultSet rs = pjr.dataComboBox()) {
            while (rs.next()) {
               
                cmbPengajar.addItem(rs.getString("nama_ustadz")); 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data Pengajar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void autoId() {
        try {
            DataKitab ktb = new DataKitab();
            ResultSet rs = ktb.autoID();
            
            if (rs.next()) {
                int id = rs.getInt("ID") + 1;
                txtIdKitab.setText(String.valueOf(id));
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "AutoID Eror : " + sQLException.getMessage());
        }
    }
    
    void resetForm() {
        txtIdKitab.setText(null);
        txtNamaKitab.setText(null);
        cmbKelas.setSelectedItem(null);
        cmbPengajar.setSelectedItem(null);
        
    }
    
    private void pencarian(String key) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kitab");
    model.addColumn("Nama Kitab");
    model.addColumn("Kelas");
    model.addColumn("Pengajar");

    try {
        DataKitab ktb = new DataKitab();
        ResultSet result = ktb.cariKitab(key);

        while (result.next()) {
            model.addRow(new Object[]{
                result.getInt("id_kitab"),
                result.getString("nama_kitab"),
                result.getString("nama_kelas"),
                result.getString("nama_ustadz")
            });
        }

        tblKitab.setModel(model);
    } catch (SQLException sQLException) {
        JOptionPane.showMessageDialog(null, "Error saat mencari : " + sQLException.getMessage());
    }
}

    void load_table() {
    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Kitab");
        model.addColumn("Nama Kitab");
        model.addColumn("Kelas");
        model.addColumn("Pengajar");

        try {
            DataKitab ktb = new DataKitab();
            ResultSet result = ktb.loadData();
            while (result.next()) {
                model.addRow(new Object[] {
                result.getInt("id_kitab"),
                result.getString("nama_kitab"),
                result.getString("nama_kelas"),
                result.getString("nama_ustadz")
            });    
            }
            tblKitab.setModel(model);
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Eror Tabel : " + sQLException);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tSearch = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        txtIdKitab = new javax.swing.JTextField();
        txtNamaKitab = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbKelas = new javax.swing.JComboBox<>();
        cmbPengajar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKitab = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tSearch.setBorder(null);
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tSearchKeyTyped(evt);
            }
        });
        add(tSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 300, 30));

        btnUbah.setBackground(new java.awt.Color(0, 0, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 90, 40));

        txtIdKitab.setBorder(null);
        txtIdKitab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKitabActionPerformed(evt);
            }
        });
        add(txtIdKitab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 350, 30));

        txtNamaKitab.setBorder(null);
        txtNamaKitab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKitabActionPerformed(evt);
            }
        });
        add(txtNamaKitab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 350, 20));

        btnHapus.setBackground(new java.awt.Color(0, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, 40));

        btnTambah.setBackground(new java.awt.Color(0, 0, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText(" Tambah");
        btnTambah.setContentAreaFilled(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("DATA KITAB");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" id_kitab");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText(" Nama Kitab");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(" Kelas");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 50, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText(" Pengajar");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 40));

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbKelas.setBorder(null);
        add(cmbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 350, 20));

        cmbPengajar.setBorder(null);
        add(cmbPengajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 350, 20));

        tblKitab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKitab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKitabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKitab);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setContentAreaFilled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data Kitab.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1055, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        DataKitab  dataKitabUbah = new DataKitab();
        DataPengajar pjr = new DataPengajar();
        DataKelas kls = new DataKelas();

        try {
            dataKitabUbah.setId_kitab(Integer.parseInt(txtIdKitab.getText()));
            dataKitabUbah.setNama_kitab(txtNamaKitab.getText());
        
        // CB Kelas
        kls.setNama_kelas(cmbKelas.getSelectedItem().toString());
        ResultSet rs = kls.konversi();
        if (rs.next()) {
            dataKitabUbah.setKelas_id(rs.getInt("id_kelas"));
        }
        
        // CB Pengajar/ustadz
        pjr.setNama_ustadz(cmbPengajar.getSelectedItem().toString());
        ResultSet rst = pjr.konversi();
        if (rst.next()) {
            dataKitabUbah.setUstadz_id(rst.getInt("id_ustadz"));
        }

        } catch (NumberFormatException | SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "BtnUbah Eror : " + sQLException.getMessage());
        }
       
        dataKitabUbah.updateData();
        resetForm();
        load_table();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtNamaKitabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKitabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKitabActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DataKitab dataKitabHapus = new DataKitab();
        dataKitabHapus.setId_kitab(Integer.parseInt(txtIdKitab.getText()));

        dataKitabHapus.deleteData();
        resetForm();
        load_table();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        //
        if (cmbKelas.getSelectedIndex() == 0 || cmbPengajar.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Pilih Kelas dan Pengajar terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DataKitab  dataKitabUbah = new DataKitab();
        DataPengajar pjr = new DataPengajar();
        DataKelas kls = new DataKelas();

        try {
        dataKitabUbah.setId_kitab(Integer.parseInt(txtIdKitab.getText()));
        dataKitabUbah.setNama_kitab(txtNamaKitab.getText());
        
        // CB Kelas
        kls.setNama_kelas(cmbKelas.getSelectedItem().toString());
        ResultSet rs = kls.konversi();
        if (rs.next()) {
            dataKitabUbah.setKelas_id(rs.getInt("id_kelas"));
        }
        
        // CB Pengajar/ustadz
        pjr.setNama_ustadz(cmbPengajar.getSelectedItem().toString());
        ResultSet rst = pjr.konversi();
        if (rst.next()) {
            dataKitabUbah.setUstadz_id(rst.getInt("id_ustadz"));
        }

        } catch (NumberFormatException | SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "BtnTambah Eror : " + sQLException.getMessage());
        }
       
        dataKitabUbah.saveData();
        resetForm();
        load_table();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtIdKitabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKitabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKitabActionPerformed

    private void tblKitabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKitabMouseClicked
        // TODO add your handling code here:
        int baris = tblKitab.getSelectedRow();
        if (baris != -1){
            String id              = tblKitab.getValueAt(baris, 0).toString();
            String nama            = tblKitab.getValueAt(baris, 1).toString();
            String kelas           = tblKitab.getValueAt(baris, 2).toString();
            String ustadz          = tblKitab.getValueAt(baris, 3).toString();

            txtIdKitab.setText(id);
            txtNamaKitab.setText(nama);
            cmbKelas.setSelectedItem(kelas);
            cmbPengajar.setSelectedItem(ustadz);
        }
    }//GEN-LAST:event_tblKitabMouseClicked

    private void tSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyTyped
        // TODO add your handling code here:
        String key = tSearch.getText();
        pencarian(key);
    }//GEN-LAST:event_tSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JComboBox<String> cmbPengajar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTable tblKitab;
    private javax.swing.JTextField txtIdKitab;
    private javax.swing.JTextField txtNamaKitab;
    // End of variables declaration//GEN-END:variables
}
