
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrame;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.DataKelas;
import kelas.DataPengajar;

/**
 *
 * @author cherly
 */
public class KelasFrame extends javax.swing.JPanel {

    public KelasFrame() {
        initComponents();
        loadTable();      // Munculkan data saat pertama kali buka
        CBWaliKelas();  // Isi ComboBox dengan nama Ustadz
        resetForm();     // Bersihkan field
        autoId();       // Otomatis Menampilkan ID 
    }

    void loadTable() {
    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Kelas");
        model.addColumn("Nama Kelas");
        model.addColumn("Wali Kelas");

        try {
            DataKelas kls = new DataKelas();
            ResultSet rs = kls.tampilKelas();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_kelas"),
                    rs.getString("nama_kelas"),
                    rs.getString("nama_ustadz")
                });
            }
            tblKelas.setModel(model);
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(this, "Eror Tabel : " + sQLException.getMessage());
        }
    }
    
    private void pencarian(String key) {
    DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Kelas");
        model.addColumn("Nama Kelas");
        model.addColumn("Wali Kelas");

    try {
        DataKelas kls = new DataKelas();
        ResultSet result = kls.cariKelas(key);

        while (result.next()) {
            model.addRow(new Object[]{
                result.getInt("id_kelas"),
                result.getString("nama_kelas"),
                result.getString("nama_ustadz")
            });
        }

        tblKelas.setModel(model);
    } catch (SQLException sQLException) {
        JOptionPane.showMessageDialog(null, "Error saat mencari : " + sQLException.getMessage());
    }
    }
    
    void CBWaliKelas() {
        if (CBWaliKelas == null) return;
            // Membersihkan item lama agar tidak duplikat saat dipanggil ulang
        CBWaliKelas.removeAllItems();
        CBWaliKelas.addItem("- Pilih Wali Kelas -"); // Item default (index 0)  

        DataPengajar pjr = new DataPengajar();
        try (ResultSet rs = pjr.dataComboBox()) {
            while (rs.next()) {
                CBWaliKelas.addItem(rs.getString("nama_ustadz"));   
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Eror CBPengajar : " + sQLException.getMessage());
        }       
}

    void resetForm() {
        tID.setText("");
        tNamaLengkap.setText("");
        CBWaliKelas.setSelectedIndex(0);
        tCari.setText("");
    }
    
    void autoId() {
        try {
            DataKelas kls = new DataKelas();
            ResultSet rs = kls.autoId();
            
            if (rs.next()) {
                int id = rs.getInt("ID") + 1;
                tID.setText(String.valueOf(id));
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "AutoID Eror : " + sQLException.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tID = new javax.swing.JTextField();
        tNamaLengkap = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        CBWaliKelas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tID.setBorder(null);
        add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 350, 20));

        tNamaLengkap.setBorder(null);
        tNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaLengkapActionPerformed(evt);
            }
        });
        add(tNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 350, 20));

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.setBorder(null);
        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText(" ID Kelas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" Wali Kelas");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("DATA KELAS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 390, 90));

        tCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tCari.setBorder(null);
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCariKeyTyped(evt);
            }
        });
        add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 280, 30));

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(null);
        btnHapus.setBorderPainted(false);
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 40));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.setBorder(null);
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 90, 40));

        CBWaliKelas.setBorder(null);
        add(CBWaliKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 350, -1));

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKelas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, 430));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(" Nama Kelas");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.setBorder(null);
        btnUbah.setBorderPainted(false);
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data Kelas.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaLengkapActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        DataKelas kls = new DataKelas();
        DataPengajar pjr = new DataPengajar();
        
        try {
            
        kls.setId_kelas(Integer.parseInt(tID.getText()));
        kls.setNama_kelas(tNamaLengkap.getText());
        
        // CB Pengajar/ustadz
        pjr.setNama_ustadz(CBWaliKelas.getSelectedItem().toString());
        ResultSet rst = pjr.konversi();
        if (rst.next()) {
            kls.setWali_ustadz_id(rst.getInt("id_ustadz"));
        }

        } catch (NumberFormatException | SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "BtnTambah Eror : " + sQLException.getMessage());
        }
       
        kls.ubahDataKelas();
        resetForm();
        loadTable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        DataKelas kls = new DataKelas();
        DataPengajar pjr = new DataPengajar();
        
        try {
//        kls.setId_kelas(Integer.parseInt(tID.getText()));
        kls.setNama_kelas(tNamaLengkap.getText());
        
        // CB Pengajar/ustadz
        pjr.setNama_ustadz(CBWaliKelas.getSelectedItem().toString());
        ResultSet rst = pjr.konversi();
        if (rst.next()) {
            kls.setWali_ustadz_id(rst.getInt("id_ustadz"));
        }

        } catch (NumberFormatException | SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "BtnTambah Eror : " + sQLException.getMessage());
        }
       
        kls.tambahDataKelas();
        resetForm();
        loadTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DataKelas kls = new DataKelas();
        kls.setId_kelas(Integer.parseInt(tID.getText()));
        
        kls.hapusDataKelas();
        resetForm();
        loadTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKelasMouseClicked
        // TODO add your handling code here:
        int baris = tblKelas.getSelectedRow();
        if (baris != -1){
            String id              = tblKelas.getValueAt(baris, 0).toString();
            String nama            = tblKelas.getValueAt(baris, 1).toString();
            String Wali            = tblKelas.getValueAt(baris, 2).toString();

            tID.setText(id);
            tNamaLengkap.setText(nama);
            CBWaliKelas.setSelectedItem(Wali);
        }
    }//GEN-LAST:event_tblKelasMouseClicked

    private void tCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyTyped
        // TODO add your handling code here:
        String key = tCari.getText();
        pencarian(key);
    }//GEN-LAST:event_tCariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBWaliKelas;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tNamaLengkap;
    private javax.swing.JTable tblKelas;
    // End of variables declaration//GEN-END:variables
}
