/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author cherly
 */
public class LogSantri extends javax.swing.JPanel {

    /**
     * Creates new form LogSantri
     */
    public LogSantri() {
        initComponents();
        tampilkanLog();
    }
   public void tampilkanLog() {
    // Membuat header tabel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama Santri");
    model.addColumn("Waktu Kejadian");
    model.addColumn("Keterangan");

    try {
        // Memanggil koneksi dari class Koneksi yang Anda buat
        kelas.Koneksi konek = new kelas.Koneksi();
        java.sql.Connection con = konek.configDB();
        
        java.sql.Statement st = con.createStatement();
        // Mengambil data dari tabel log_santri, yang terbaru di atas
        String sql = "SELECT nama, waktu, keterangan FROM log_santri ORDER BY waktu DESC";
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nama"),
                rs.getString("waktu"),
                rs.getString("keterangan")
            });
        }
        
        // Memasukkan model ke jTable1
        jTable1.setModel(model);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat log: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1105, 715));
        setMinimumSize(new java.awt.Dimension(1105, 715));
        setPreferredSize(new java.awt.Dimension(1105, 715));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 270, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setText("Search :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 70, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 860, 430));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LOG SANTRI ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 320, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogSantri.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
                      
    String cari = jTextField1.getText();
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Log");
    model.addColumn("Nama Santri");
    model.addColumn("Waktu");
    model.addColumn("Keterangan");

    try {
        kelas.Koneksi konek = new kelas.Koneksi();
        java.sql.Connection con = konek.configDB();
        
        // Gunakan LIKE untuk pencarian
        String sql = "SELECT * FROM log_mahasiswa WHERE nama LIKE ? OR keterangan LIKE ? ORDER BY waktu DESC";
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "%" + cari + "%");
        ps.setString(2, "%" + cari + "%");
        
        java.sql.ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("nama"),
                rs.getString("waktu"),
                rs.getString("keterangan")
            });
        }
        jTable1.setModel(model);
        
    } catch (Exception e) {
        System.err.println(e.getMessage());
    }

    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
